### ISSUE TITLE
Top bar disappears on PC

### ISSUE THREAD

**Issue by coding-CEO** [CircuitVerse/Interactive-Book#261]
How to reproduce the issue : 

**1) Go to the home page.**

![NPAVScSt](https://user-images.githubusercontent.com/52625909/81033921-fee58900-8eb2-11ea-80c0-53934f4152b5.jpg)

**2) Close the sidebar**

![NPAVScSt (2)](https://user-images.githubusercontent.com/52625909/81033926-02791000-8eb3-11ea-8db4-d34223bf9563.jpg)

**3) reduce the width of browser.**

![NPAVScSt (3)](https://user-images.githubusercontent.com/52625909/81033936-09a01e00-8eb3-11ea-8388-ea3bfe084a35.jpg)

NOTE:-> I think this will work nicely directly on mobile.

**Comment by coding-CEO** [comment]
I fixed this problem in the PR #263 
So, please review it.

**Comment by abhinavsri360** [comment]
I don't find the issue fixed, it still persists and the sidebar button vanishes on reducing the window size.

**Comment by abhinavsri360** [comment]
![image](https://user-images.githubusercontent.com/44001310/82043789-d2f3b000-96c9-11ea-89e1-c5d58c3be2b7.png)
