### ISSUE TITLE
Reference is only text

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/Interactive-Book#37]
Feature request
In reference section 
What ever references are written it is only in TEXT format ,make it such that when ever we click in that link of reference we redirect to that link

**Comment by NamanZelawat** [comment]
@dev9414 I am Naman Zelawat, can I work on it. I am a new contributor and want some basic issues to contribute.

**Comment by Ananthavijay** [comment]
@NamanZelawat It seems that this issue has already been fixed in this [Pull Request](https://github.com/CircuitVerse/Interactive-Book/pull/222)

**Comment by NamanZelawat** [comment]
But there was no change in the official site so I thought maybe It was not fixed.

**Comment by NamanZelawat** [comment]
Thanks for your response @dev9414 have a good day :).

**Comment by NamanZelawat** [comment]
@Ananthavijay I can't see any changes in the master branch also shall I generate my pull request or not.

**Comment by abhinavsri360** [comment]
This issue is also resolved.
Close the same @YashKumarVerma
