### ISSUE TITLE
Enable scrolling in search drop-down

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#447]
## Describe the bug
Whenever the user types something in the search bar, It shows a long list of pages, extending the current page length. 

## To Reproduce

1.  Go to 'learn.circuitverse.org'
2.  Click on 'Search'
3.  Type Something in the search bar
4.  See error

## Expected behavior

We should enable vertical scrolling, showing maximum of 5 results at a time so that the drop-down does not stretches the page and also looks good to the user.

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

**Comment by shubhdeep123** [comment]
Fixed the search bar issue. And vertical scrolling enabled with max to 5 results at a time.
![IMG20200702231439](https://user-images.githubusercontent.com/64921946/86392970-f1355f80-bcb9-11ea-9cbd-b1cd20adfc65.jpg)

**Comment by singhanurag05** [comment]
I see the issue still exists on the Interactive book can I try this?

**Comment by SingingApple** [comment]
I see this issue is still up. Can I work on it?

**Comment by Shivansh2407** [comment]
Fixed in #455 by @shubhdeep123
